version: '3'
services:
  web:
    container_name: music-front
    image: ghcr.io/heavyrisem/music_front
    networks:
      - music_net
      - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1

networks:
  music_net:
    external: true
  nginx:
    external: true
