version: '3'

services:
  music_front_runner:
    container_name: music-front-runner
    image: interaction/github-actions-runner:latest
    restart: always
    environment:
      RUNNER_WORKDIR: /_work
    env_file:
      - .env.runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./_work:/_work
